package com.example.asm.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;

@Configuration
public class ProductTypeBootstrapConfig {

    @Bean
    @Order(2)
    CommandLineRunner productTypeSchemaRunner(JdbcTemplate jdbcTemplate) {
        return args -> jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS LoaiHang (
                    MaLoaiHang INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    TenLoaiHang VARCHAR(150) NOT NULL UNIQUE,
                    MoTa VARCHAR(500),
                    TrangThai BOOLEAN NOT NULL DEFAULT TRUE
                )
                """);
    }
}
